project_name: doras
version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: doras-server
    binary: doras-server-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    main: ./cmd/doras-server
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      "-s -w -X main.version={{.Tag}}"

  - id: doras-cli
    binary: doras-cli-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    main: ./cmd/doras-cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X main.build={{.Version}}
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    allow_different_binary_count: true

kos:
  - id: doras-server
    build: doras-server
    main: ./cmd/doras-server
    working_dir: .
    base_image: cgr.dev/chainguard/static
    repositories:
      - ghcr.io/unbasical/doras-server
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"
    bare: true
    sbom: spdx
    ldflags:
      - "-s -w -X main.version={{.Tag}}"
  - id: doras-cli
    build: doras-cli
    main: ./cmd/doras-cli
    working_dir: .
    base_image: cgr.dev/chainguard/static
    repositories:
      - ghcr.io/unbasical/doras-cli
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"
    bare: true
    sbom: spdx

sboms:
  - documents:
      - "${artifact}.spdx.sbom.json"
    cmd: syft
    args: ["$artifact", "--output", "spdx-json=$document"]
    artifacts: binary
    ids:
      - doras-server
      - doras-cli


changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: false
  github:
    owner: unbasical
    name: doras
  footer: >-

    ---
