services:
  doras-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DORAS_HOST: 0.0.0.0
      DORAS_INSECURE_ALLOW_HTTP: True
      DORAS_LOG_LEVEL: debug

  registry:
    image: registry:2.8
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "/registry-storage"
    volumes:
      - registry-storage:/registry-storage
    ports:
      - "5001:5000"
volumes:
  registry-storage: