POST http://localhost:8080/api/v1/edge/artifacts/delta/create
content-type: application/json

{
  "identifier": "hello-world.txt",
  "hash": "d2a84f4b8b650937ec8f73cd8be2c74add5a911ba64df27458ed8229da804a26"
}
