info:
  contact: {}
paths:
  /api/v1/artifacts/create:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: message":"pong"}
          schema:
            type: string
      summary: ping example
      tags:
      - CloudAPI
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: message":"pong"}
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
